### ISSUE TITLE
Please add rust-la to crates.io

### ISSUE THREAD

**Issue by astraw** [xasmx/rust-la#2]
It would be great to add rust-la to [crates.io](https://crates.io) so that projects can depend on it using the Cargo.toml file.

**Comment by astraw** [comment]
Of course, one can add rust-la to Cargo.toml with this:

```
[dependencies.la]
git = "https://github.com/xasmx/rust-la.git"
```

**Comment by xasmx** [comment]
Added rust-la to crates.io:

[dependencies]
la = "0.1.0"
